// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bison.DBService.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20261007184302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Bison.Core.models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Bison.Core.models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Post");

                    b.HasDiscriminator().HasValue("Post");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Bison.Core.models.Taxon", b =>
                {
                    b.Property<string>("TaxonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentTaxonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VernacularName")
                        .HasColumnType("TEXT");

                    b.HasKey("TaxonId");

                    b.HasIndex("ParentTaxonId");

                    b.ToTable("taxons");
                });

            modelBuilder.Entity("Bison.Core.models.Comment", b =>
                {
                    b.HasBaseType("Bison.Core.models.Post");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ObservationId");

                    b.HasDiscriminator().HasValue("Comment");
                });

            modelBuilder.Entity("Bison.Core.models.Observation", b =>
                {
                    b.HasBaseType("Bison.Core.models.Post");

                    b.Property<string>("TaxonId")
                        .HasColumnType("TEXT");

                    b.HasIndex("TaxonId");

                    b.HasDiscriminator().HasValue("Observation");
                });

            modelBuilder.Entity("Bison.Core.models.Proposal", b =>
                {
                    b.HasBaseType("Bison.Core.models.Post");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("ObservationId");

                    b.HasIndex("TaxonId");

                    b.ToTable("Post", t =>
                        {
                            t.Property("ObservationId")
                                .HasColumnName("Proposal_ObservationId");

                            t.Property("TaxonId")
                                .HasColumnName("Proposal_TaxonId");
                        });

                    b.HasDiscriminator().HasValue("Proposal");
                });

            modelBuilder.Entity("Bison.Core.models.Post", b =>
                {
                    b.HasOne("Bison.Core.models.Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Bison.Core.models.Taxon", b =>
                {
                    b.HasOne("Bison.Core.models.Taxon", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentTaxonId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Bison.Core.models.Comment", b =>
                {
                    b.HasOne("Bison.Core.models.Observation", "Observation")
                        .WithMany("Comments")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("Bison.Core.models.Observation", b =>
                {
                    b.HasOne("Bison.Core.models.Taxon", "Taxon")
                        .WithMany()
                        .HasForeignKey("TaxonId");

                    b.Navigation("Taxon");
                });

            modelBuilder.Entity("Bison.Core.models.Proposal", b =>
                {
                    b.HasOne("Bison.Core.models.Observation", "Observation")
                        .WithMany("Proposals")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bison.Core.models.Taxon", "Taxon")
                        .WithMany()
                        .HasForeignKey("TaxonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");

                    b.Navigation("Taxon");
                });

            modelBuilder.Entity("Bison.Core.models.Author", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Bison.Core.models.Taxon", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Bison.Core.models.Observation", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
