// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bison.DBService.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Bison.Core.models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentVal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("Bison.Core.models.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxonID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("proposals");
                });

            modelBuilder.Entity("Bison.Core.models.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("readings");
                });

            modelBuilder.Entity("Bison.Core.models.Taxon", b =>
                {
                    b.Property<string>("TaxonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentTaxonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxonRank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VernacularName")
                        .HasColumnType("TEXT");

                    b.HasKey("TaxonId");

                    b.HasIndex("ParentTaxonId");

                    b.ToTable("taxons");
                });

            modelBuilder.Entity("Bison.Core.models.Taxon", b =>
                {
                    b.HasOne("Bison.Core.models.Taxon", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentTaxonId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Bison.Core.models.Taxon", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
